default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(
      task: "clean bundle",
      build_type: "Release"
    )

    upload_to_play_store(
      package_name: "com.kaya.musicapp",
      release_status: "draft",
      aab: "../build/app/outputs/bundle/release/app-release.aab"
    )
  end
end
